apiVersion: v1
kind: Endpoints
metadata:
  name: peerbot-loadbalancer
  namespace: peerbot
subsets:
- addresses:
  - ip: 10.107.129.20
  - ip: 10.107.129.19
  ports:
  - name: http
    port: 3000
    protocol: TCP