apiVersion: v1
kind: Service
metadata:
  name: peerbot-nodeport
  namespace: peerbot
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: dispatcher
    app.kubernetes.io/instance: peerbot
    app.kubernetes.io/name: peerbot
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30300
    name: http