apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "peerbot.fullname" . }}-config
  labels:
    {{- include "peerbot.labels" . | nindent 4 }}
data:
  # GCS Configuration
  gcs-bucket-name: {{ .Values.config.gcsBucketName | quote }}
  {{- if .Values.config.gcsProjectId }}
  gcs-project-id: {{ .Values.config.gcsProjectId | quote }}
  {{- end }}
  
  # GitHub Configuration
  github-organization: {{ .Values.config.githubOrganization | quote }}
  
  # Session Configuration
  session-timeout-minutes: {{ .Values.config.sessionTimeoutMinutes | quote }}
  
  # Claude Configuration
  claude-model: {{ .Values.claude.model | quote }}
  claude-timeout-minutes: {{ .Values.claude.timeoutMinutes | quote }}
  {{- if .Values.claude.allowedTools }}
  claude-allowed-tools: {{ .Values.claude.allowedTools | quote }}
  {{- end }}
  
  # Worker Configuration
  worker-cpu: {{ .Values.worker.resources.requests.cpu | quote }}
  worker-memory: {{ .Values.worker.resources.requests.memory | quote }}
  worker-timeout-seconds: {{ .Values.worker.job.timeoutSeconds | quote }}
  worker-ttl-seconds: {{ .Values.worker.job.ttlSecondsAfterFinished | quote }}
  
  # Slack Configuration
  slack-trigger-phrase: {{ .Values.slack.triggerPhrase | quote }}
  slack-socket-mode: {{ .Values.slack.socketMode | quote }}
  slack-allow-direct-messages: {{ .Values.slack.allowDirectMessages | quote }}
  slack-allow-private-channels: {{ .Values.slack.allowPrivateChannels | quote }}
  slack-enable-status-reactions: {{ .Values.slack.enableStatusReactions | quote }}
  slack-enable-progress-updates: {{ .Values.slack.enableProgressUpdates | quote }}