{{- if and .Values.keda.enabled (not .Values.autoscaling.enabled) }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "peerbot.fullname" . }}-dispatcher
  labels:
    {{- include "peerbot.labels" . | nindent 4 }}
    app.kubernetes.io/component: dispatcher
spec:
  scaleTargetRef:
    name: {{ include "peerbot.fullname" . }}-dispatcher
  pollingInterval: {{ .Values.keda.pollingInterval | default 30 }}
  cooldownPeriod: {{ .Values.keda.cooldownPeriod | default 300 }}  # 5 minutes
  idleReplicaCount: {{ .Values.keda.idleReplicaCount | default 0 }}  # Scale to zero
  minReplicaCount: {{ .Values.keda.minReplicaCount | default 0 }}
  maxReplicaCount: {{ .Values.keda.maxReplicaCount | default 5 }}
  triggers:
    {{- if .Values.keda.triggers.cpu }}
    - type: cpu
      metricType: Utilization
      metadata:
        value: "{{ .Values.keda.triggers.cpu.utilizationPercentage }}"
    {{- end }}
    {{- if .Values.keda.triggers.memory }}
    - type: memory
      metricType: Utilization  
      metadata:
        value: "{{ .Values.keda.triggers.memory.utilizationPercentage }}"
    {{- end }}
    {{- if .Values.keda.triggers.prometheus }}
    # Custom Prometheus metrics for more intelligent scaling
    - type: prometheus
      metadata:
        serverAddress: {{ .Values.keda.triggers.prometheus.serverAddress }}
        metricName: {{ .Values.keda.triggers.prometheus.metricName }}
        threshold: "{{ .Values.keda.triggers.prometheus.threshold }}"
        query: {{ .Values.keda.triggers.prometheus.query }}
    {{- end }}
{{- end }}