{{- if .Values.orchestrator.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "peerbot.fullname" . }}-orchestrator
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "peerbot.labels" . | nindent 4 }}
    app.kubernetes.io/component: orchestrator
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "peerbot.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: orchestrator
{{- end }}