apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "peerbot.fullname" . }}-postgresql-init
  namespace: {{ .Values.kubernetes.namespace }}
  labels:
    {{- include "peerbot.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
data:
  01-init-pgboss.sql: |
    -- Create pgboss schema and user
    CREATE SCHEMA IF NOT EXISTS pgboss;
    
    -- Grant permissions to main user
    GRANT ALL PRIVILEGES ON SCHEMA pgboss TO {{ .Values.postgresql.username }};
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA pgboss TO {{ .Values.postgresql.username }};
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA pgboss TO {{ .Values.postgresql.username }};
    
    -- Set default privileges for future objects
    ALTER DEFAULT PRIVILEGES IN SCHEMA pgboss GRANT ALL ON TABLES TO {{ .Values.postgresql.username }};
    ALTER DEFAULT PRIVILEGES IN SCHEMA pgboss GRANT ALL ON SEQUENCES TO {{ .Values.postgresql.username }};
    
  02-init-schema.sql: |
    -- Load the main schema migration
    \i /docker-entrypoint-initdb.d/schema-001_initial_schema.sql
    \i /docker-entrypoint-initdb.d/schema-002_queue_tables.sql
    \i /docker-entrypoint-initdb.d/schema-003_pgboss_rls_fix.sql
    
  schema-001_initial_schema.sql: |
{{ .Files.Get "../../db/migrations/001_initial_schema.sql" | indent 4 }}
    
  schema-002_queue_tables.sql: |
{{ .Files.Get "../../db/migrations/002_queue_tables.sql" | indent 4 }}
    
  schema-003_pgboss_rls_fix.sql: |
{{ .Files.Get "../../db/migrations/003_pgboss_rls_fix.sql" | indent 4 }}