apiVersion: v1
kind: Service
metadata:
  name: {{ include "peerbot.fullname" . }}-postgresql
  namespace: {{ .Values.kubernetes.namespace }}
  labels:
    {{- include "peerbot.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  ports:
  - name: postgresql
    port: 5432
    targetPort: postgresql
    protocol: TCP
  selector:
    {{- include "peerbot.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql