{{- if and .Values.ingress.enabled (not .Values.ingress.className) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "peerbot.fullname" . }}-loadbalancer
  namespace: {{ .Values.kubernetes.namespace }}
  labels:
    {{- include "peerbot.labels" . | nindent 4 }}
    component: dispatcher
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: {{ .Values.slack.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "peerbot.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: dispatcher
{{- end }}