apiVersion: v1
kind: Service
metadata:
  name: {{ include "peerbot.fullname" . }}-dispatcher
  labels:
    {{- include "peerbot.labels" . | nindent 4 }}
    app.kubernetes.io/component: dispatcher
spec:
  type: {{ .Values.dispatcher.service.type }}
  ports:
    - port: {{ .Values.dispatcher.service.port }}
      targetPort: {{ .Values.dispatcher.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "peerbot.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: dispatcher