name: Claude Args Example

on:
  workflow_dispatch:
    inputs:
      prompt:
        description: "Prompt for Claude"
        required: true
        type: string

jobs:
  claude-with-custom-args:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Claude with custom arguments
        uses: anthropics/claude-code-action@v1-dev
        with:
          prompt: ${{ github.event.inputs.prompt }}
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}

          # claude_args provides direct CLI argument control
          # This allows full customization of Claude's behavior
          claude_args: |
            --max-turns 15
            --model claude-opus-4-1-20250805
            --allowedTools Edit,Read,Write,Bash
            --disallowedTools WebSearch
            --system-prompt "You are a senior engineer focused on code quality"
