name: Claude Automatic Mode Detection Examples

on:
  # Events for interactive mode (responds to @claude mentions)
  issue_comment:
    types: [created]
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened]
  # Events for automation mode (runs with explicit prompt)
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # Weekly on Sunday

jobs:
  # Interactive Mode - Activated automatically when no prompt is provided
  interactive-mode-example:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
    steps:
      - uses: anthropics/claude-code-action@v1-dev
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          # Interactive mode (auto-detected when no prompt):
          # - Scans for @claude mentions in comments, issues, and PRs
          # - Only acts when trigger phrase is found
          # - Creates tracking comments with progress checkboxes
          # - Perfect for: Interactive Q&A, on-demand code changes

  # Automation Mode - Activated automatically when prompt is provided
  automation-mode-scheduled-task:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
    steps:
      - uses: anthropics/claude-code-action@v1-dev
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          prompt: |
            Check for outdated dependencies and security vulnerabilities.
            Create an issue if any critical problems are found.
          # Automation mode (auto-detected when prompt provided):
          # - Works with any GitHub event
          # - Executes immediately without waiting for @claude mentions
          # - No tracking comments created
          # - Perfect for: scheduled maintenance, automated reviews, CI/CD tasks
