stages:
  - claude

claude-code:
  stage: claude
  image: node:20
  rules:
    - if: $CI_MERGE_REQUEST_IID
  script:
    - npx claude-code-action --provider gitlab --project-id $CI_PROJECT_ID \
      --mr-iid $CI_MERGE_REQUEST_IID --gitlab-host $CI_SERVER_URL
  variables:
    GITLAB_TOKEN: $GITLAB_TOKEN
    ANTHROPIC_API_KEY: $ANTHROPIC_API_KEY
