name: Claude Review - Specific Authors

# This workflow supports fork PRs. See docs/fork-pr-support.md for details.

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  review-by-author:
    # Only run for PRs from specific authors
    if: |
      github.event.pull_request.user.login == 'developer1' ||
      github.event.pull_request.user.login == 'developer2' ||
      github.event.pull_request.user.login == 'external-contributor'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
      actions: read
    steps:
      # Checkout fork repository for fork PR support
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Review PR from Specific Author
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          # Required for fork PR support with pull_request_target
          github_token: ${{ secrets.GITHUB_TOKEN }}
          allowed_non_write_users: '*'
          prompt: |
            REPO: ${{ github.repository }}
            PR NUMBER: ${{ github.event.pull_request.number }}

            Please provide a thorough review of this pull request.

            Note: The PR branch is already checked out in the current working directory.

            Since this is from a specific author that requires careful review,
            please pay extra attention to:
            - Adherence to project coding standards
            - Proper error handling
            - Security best practices
            - Test coverage
            - Documentation

            Provide detailed feedback and suggestions for improvement.

          claude_args: |
            --allowedTools "mcp__github_inline_comment__create_inline_comment,Bash(gh pr comment:*), Bash(gh pr diff:*), Bash(gh pr view:*)"
