name: Claude Review - Path Specific

# This workflow supports fork PRs. See docs/fork-pr-support.md for details.

on:
  pull_request_target:
    types: [opened, synchronize]
    paths:
      # Only run when specific paths are modified
      - "src/**/*.js"
      - "src/**/*.ts"
      - "api/**/*.py"
      # You can add more specific patterns as needed

jobs:
  claude-review-paths:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
      actions: read
    steps:
      # Checkout fork repository for fork PR support
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Claude Code Review
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          # Required for fork PR support with pull_request_target
          github_token: ${{ secrets.GITHUB_TOKEN }}
          allowed_non_write_users: '*'
          prompt: |
            REPO: ${{ github.repository }}
            PR NUMBER: ${{ github.event.pull_request.number }}

            Please review this pull request focusing on the changed files.

            Note: The PR branch is already checked out in the current working directory.

            Provide feedback on:
            - Code quality and adherence to best practices
            - Potential bugs or edge cases
            - Performance considerations
            - Security implications
            - Suggestions for improvement

            Since this PR touches critical source code paths, please be thorough
            in your review and provide inline comments where appropriate.

          claude_args: |
            --allowedTools "mcp__github_inline_comment__create_inline_comment,Bash(gh pr comment:*), Bash(gh pr diff:*), Bash(gh pr view:*)"
