name: PR Review with Session Caching

# This example demonstrates how to use session caching with commit tracking
# to enable incremental PR reviews. Claude remembers context across commits
# and only reviews new changes after the first review.

on:
  pull_request:
    types: [opened, synchronize]

env:
  # Full prompt for first review (comprehensive)
  PROMPT_FULL: |
    REPO: ${{ github.repository }}
    PR NUMBER: ${{ github.event.pull_request.number }}
    COMMIT: ${{ github.event.pull_request.head.sha }}

    ## 🎯 FIRST REVIEW - Comprehensive Analysis

    This is the first review of this pull request. Perform a thorough analysis covering:

    **1. Code Quality**
    - Clean code principles and best practices
    - Proper error handling and edge cases
    - Code readability and maintainability

    **2. Security**
    - Check for potential security vulnerabilities
    - Validate input sanitization
    - Review authentication/authorization logic

    **3. Performance**
    - Identify potential performance bottlenecks
    - Review database queries for efficiency
    - Check for memory leaks or resource issues

    **4. Testing**
    - Verify adequate test coverage
    - Review test quality and edge cases
    - Check for missing test scenarios

    **5. Documentation**
    - Ensure code is properly documented
    - Verify README updates for new features
    - Check API documentation accuracy

    Note: The PR branch is already checked out in the current working directory.

    Provide detailed feedback using inline comments for specific issues.
    Use top-level comments for general observations.

  # Simple prompt for subsequent reviews (incremental)
  PROMPT_SIMPLE: |
    REPO: ${{ github.repository }}
    PR NUMBER: ${{ github.event.pull_request.number }}
    COMMIT: ${{ github.event.pull_request.head.sha }}
    LAST COMMIT REVIEWED: {LAST_COMMIT}

    ## 🔄 INCREMENTAL REVIEW - Changes Since Last Review

    Review ONLY the changes since your last review at commit {LAST_COMMIT}.

    **How to detect changes:**
    1. Use: `git log --oneline {LAST_COMMIT}..HEAD` to see new commits
    2. Use: `git diff {LAST_COMMIT}..HEAD` to see all changes
    3. Focus only on what changed since {LAST_COMMIT}

    **Review Focus:**
    - New code changes and additions
    - Modified functionality
    - Potential issues introduced in new commits
    - Consistency with previously reviewed code

    **Important:**
    - Don't re-review unchanged code
    - Update previous comments if issues were addressed
    - Mention if previously identified issues remain

    Note: The PR branch is already checked out in the current working directory.

    Provide concise feedback focused on the new changes only.

jobs:
  review-with-caching:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0  # Full history for git diff/log operations

      - name: Cache Claude Session
        id: cache_session
        continue-on-error: true
        uses: actions/cache@v4
        with:
          path: ~/.claude/projects
          key: claude-review-${{ github.event.pull_request.number }}-${{ github.event.pull_request.head.sha }}
          restore-keys: |
            claude-review-${{ github.event.pull_request.number }}-

      - name: Load Review Prompt
        id: load_prompt
        shell: bash
        run: |
          # Check if this is a continuation of a previous review
          COMMIT_FILE=~/.claude/projects/.last-reviewed-commit
          
          if [ -f "$COMMIT_FILE" ]; then
            LAST_COMMIT=$(cat "$COMMIT_FILE")
            echo "📍 Found last reviewed commit: $LAST_COMMIT"
            echo "HAS_PREVIOUS_SESSION=true" >> $GITHUB_OUTPUT
            
            # Use simple prompt and inject LAST_COMMIT variable
            PROMPT="${{ env.PROMPT_SIMPLE }}"
            PROMPT="${PROMPT//\{LAST_COMMIT\}/$LAST_COMMIT}"
            echo "📝 Using incremental review prompt"
          else
            echo "📍 No previous commit found (first review or cache miss)"
            echo "HAS_PREVIOUS_SESSION=false" >> $GITHUB_OUTPUT
            
            # Use full prompt
            PROMPT="${{ env.PROMPT_FULL }}"
            echo "📝 Using comprehensive review prompt"
          fi
          
          # Set the prompt as an environment variable for the next step
          echo "REVIEW_PROMPT<<EOF" >> $GITHUB_ENV
          echo "$PROMPT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          
          echo "✅ Prompt loaded successfully"

      - name: PR Review with Progress Tracking
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          track_progress: true
          prompt: ${{ env.REVIEW_PROMPT }}
          claude_args: |
            --allowedTools "mcp__github_inline_comment__create_inline_comment,Bash(gh pr comment:*),Bash(gh pr diff:*),Bash(gh pr view:*),Bash(git diff:*),Bash(git log:*),Bash(git cat-file:*)"
            ${{ steps.load_prompt.outputs.HAS_PREVIOUS_SESSION == 'true' && '--continue' || '' }}

      - name: Save Last Reviewed Commit
        if: success()
        shell: bash
        run: |
          COMMIT_FILE=~/.claude/projects/.last-reviewed-commit
          mkdir -p "$(dirname "$COMMIT_FILE")"
          echo "${{ github.event.pull_request.head.sha }}" > "$COMMIT_FILE"
          echo "✅ Saved commit SHA to $COMMIT_FILE"
          echo "   This will be cached for the next review"

# How Session Caching Works:
#
# First Commit (Full Review):
# 1. No cached session exists, no .last-reviewed-commit file
# 2. Loads PROMPT_FULL (comprehensive review instructions)
# 3. Claude performs full PR review
# 4. Saves commit SHA to .last-reviewed-commit
# 5. Session cached with key: claude-review-{PR_NUMBER}-{COMMIT_SHA}
#
# Subsequent Commits (Incremental Review):
# 1. Cache restored from previous commit (via restore-keys prefix match)
# 2. Reads .last-reviewed-commit to get previous commit SHA
# 3. Loads PROMPT_SIMPLE with LAST_COMMIT variable injected
# 4. Claude uses --continue flag to resume from previous session
# 5. Reviews ONLY changes since LAST_COMMIT (using git diff/log)
# 6. Saves new commit SHA to .last-reviewed-commit
# 7. Session cached with new key (includes current commit SHA)
#
# Benefits:
# - ⚡ Faster reviews - No re-analysis of entire PR every commit
# - 🧠 Context preservation - Remembers previous discussions and decisions
# - 🎯 Focused feedback - Only reviews new changes
# - 💾 Per-PR isolation - Each PR has its own cache namespace
