name: Claude Auto Review Test

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to review'
        required: false
        type: string

jobs:
  auto-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Automatic PR Review
        uses: anthropics/claude-code-action@v1-dev
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          timeout_minutes: "60"
          prompt: |
            Please review this pull request and provide comprehensive feedback.

            Focus on:
            - Code quality and best practices
            - Potential bugs or issues
            - Performance considerations
            - Security implications
            - Test coverage
            - Documentation updates if needed

            Provide constructive feedback with specific suggestions for improvement.
            Use inline comments to highlight specific areas of concern.
            
            After your review, submit a proper GitHub review with your findings.
          claude_args: |
            --allowed-tools mcp__github-comment-server__create_pending_pull_request_review
            --allowed-tools mcp__github-comment-server__add_comment_to_pending_review
            --allowed-tools mcp__github-comment-server__submit_pending_pull_request_review
            --allowed-tools mcp__github-comment-server__get_pull_request_diff
            --allowed-tools mcp__github-comment-server__get_pull_request_files
            --allowed-tools mcp__github-comment-server__get_pull_request
            --allowed-tools mcp__github-comment-server__list_pull_request_reviews
            --allowed-tools mcp__github-comment-server__list_pull_request_review_comments
